### ISSUE TITLE
PCP Dashboard Not found in Grafana 8.2.3 

### ISSUE THREAD

**Issue by karthi12346** [performancecopilot/grafana-pcp#92]
PCP vector checklist and other dashboards are launched fine in grafana 7.5.3 but with grafana 8.x "Dashboard not found" error disaplyed.

![image](https://user-images.githubusercontent.com/12741863/141774696-6fbce04e-76eb-47ae-a9cf-6555a135c30b.png)

**Comment by andreasgerstmayr** [comment]
Did you enable the plugin?

I tried to reproduce it:
```
podman run -e GF_INSTALL_PLUGINS="https://github.com/performancecopilot/grafana-pcp/releases/download/v3.2.0/performancecopilot-pcp-app-3.2.0.zip;performancecopilot-pcp-app" -p 3001:3000 docker.io/grafana/grafana
```

Settings -> Plugins -> Performance Co-Pilot -> Config -> Enable

And it shows all checklist dashboards. There are more dashboards in the PCP Vector datasource settings page, Dashboards tab.

I noticed however that while the "PCP Vector: Host Overview" dashboard works, the checklist dashboards don't work with Grafana 8.2.2 (`this.state is null`). I'll look into it.

**Comment by szEvEz** [comment]
Running into the same issue as @karthi12346 

In addition, when trying to open the "Performance Co-Pilot -> Metric Search" the following issue appears

```
An unexpected error happened
TypeError: e.spacing is not a function

t@https://$OUR_URL/public/plugins/performancecopilot-pcp-app/module.js:2:101225
v@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2226050
WithTheme(undefined)
div
t@https://$OUR_URL/public/plugins/performancecopilot-pcp-app/module.js:2:106802
v@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2226050
div
div
div
t@https://$OUR_URL/public/plugins/performancecopilot-pcp-app/module.js:2:57925
WithTheme(undefined)
t@https://$OUR_URL/public/plugins/performancecopilot-pcp-app/module.js:2:54604
c@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2223823
t@https://$OUR_URL/public/plugins/performancecopilot-pcp-app/module.js:2:124222
e@https://$OUR_URL/public/build/AppRootPage.9380a709568b1caa9c4e.js:1:1551
x@https://$OUR_URL/public/build/AppRootPage.9380a709568b1caa9c4e.js:1:3639
n@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2198359
yr@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:6160:125
t@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2245710
t@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2247697
main
t@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2242376
div
Fa@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:2140:1022
./public/app/core/utils/ConfigProvider.tsx/u<@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:4292:25637
dl@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:2835:458
ul@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:2835:745
c@https://$OUR_URL/public/build/8529.9380a709568b1caa9c4e.js:2:2223823
zr@https://$OUR_URL/public/build/8966.9380a709568b1caa9c4e.js:6173:217
```

The "Live Host Overview" Dashboard seems to be missing as well.

Running 
* Grafana v8.2.3
* grafana-pcp 3.2.0

**Comment by andreasgerstmayr** [comment]
@karthi12346: I could reproduce the issue now. The dashboard link in the navigation bar is indeed broken (it works when accessing the dashboard through the Dashboards -> Browse menu). This is a bug in upstream Grafana and affecting all Application Plugins, see https://github.com/grafana/grafana/issues/33808#issuecomment-979200423

@szEvEz: Thanks for the bug report. I fixed this issue and released grafana-pcp v3.2.1.

I'll close this ticket now, as all issues were addressed. I've opened a follow-up issue at #93 to make the troubleshooting panels of the PCP Vector Checklist dashboards work again with Grafana v8.
